"""Generates the table benchmark documents in this folder.

Wide Tables.md   - tables far wider than a 1200px window, so they clip today and wrap once
                   design/Table Cell Wrapping.md is in.
Fitted Tables.md - the same structure with short cells, so every table fits and no row wraps.

Deterministic: rerunning produces identical files, so a capture before and after a change
scrolls the same document. Run from the repo root: python design/samples/make-table-samples.py
"""

import os

WORDS = ("layout anchorable pane document floating window serializer content title selected "
         "focused activation orientation docked hidden panel group side remembered element "
         "measure arrange render cache bitmap composite transform offset viewport margin").split()

SECTIONS = 80
ROWS = 10


def words(seed, count):
    return " ".join(WORDS[(seed * 7 + i * 13) % len(WORDS)] for i in range(count))


def prose(seed):
    return (f"Section {seed} describes how the {words(seed, 3)} interacts with the {words(seed + 1, 4)}. "
            f"It is ordinary paragraph text so scrolling mixes tables with wrapped prose, "
            f"and it mentions `{WORDS[seed % len(WORDS)]}` and **{WORDS[(seed + 5) % len(WORDS)]}** once each.")


def wide_row(s, r):
    seed = s * ROWS + r
    contents = (f"The {words(seed, 6)}: `{WORDS[seed % len(WORDS)].title()}Panel` / "
                f"`{WORDS[(seed + 3) % len(WORDS)].title()}Group` with **{words(seed + 2, 2)}**, "
                f"{words(seed + 4, 14 + seed % 12)}.")
    notes = f"{words(seed + 9, 6 + seed % 5)}"
    return f"| `{WORDS[seed % len(WORDS)].title()}{r}` | {contents} | {notes} | {seed % 97} |"


def fitted_row(s, r):
    seed = s * ROWS + r
    return f"| `{WORDS[seed % len(WORDS)].title()}{r}` | {words(seed, 2)} | {words(seed + 9, 1)} | {seed % 97} |"


def document(title, row):
    lines = [f"# {title}", "", "Generated by make-table-samples.py. Do not edit by hand.", ""]
    for s in range(SECTIONS):
        lines += [f"## {s + 1}. {words(s, 2).title()}", "", prose(s), "", prose(s + 100), "",
                  "| Element | Contents | Notes | Count |", "|---|---|:---:|---:|"]
        lines += [row(s, r) for r in range(ROWS)]
        lines += [""]
    return "\n".join(lines)


here = os.path.dirname(os.path.abspath(__file__))
for name, title, row in (("Wide Tables.md", "Wide tables", wide_row),
                         ("Fitted Tables.md", "Fitted tables", fitted_row)):
    with open(os.path.join(here, name), "w", encoding="utf-8", newline="\n") as f:
        f.write(document(title, row))
